# Generated by Django 5.2.8 on 2025-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=500, verbose_name='Author')),
                ('text', models.TextField(verbose_name='Testimonial Text')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Client Photo')),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
