# Generated by Django 5.2.8 on 2025-11-28 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_orderproduct_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitant_name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Solicitant Full Name (String)')),
                ('solicitant_contact', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Solicitant Contact (Email/Phone)')),
                ('solicitant_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Solicitant Address (optional)')),
                ('order_identified', models.CharField(blank=True, max_length=100, null=True, verbose_name='Order Identifier')),
                ('anonymous_user_cookie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Anonymous User Cookie')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid (estaPagado)')),
                ('status', models.CharField(choices=[('EN_CARRITO', 'IN CART'), ('SOLICITADO', 'SOLICITED'), ('ENCARGADO', 'ORDERED'), ('RECIBIDO_NATURSUR', 'RECEIVED BY NATURSUR'), ('RECOGIDO_CLIENTE', 'PICKED UP BY CLIENT')], default='SOLICITADO', max_length=20, verbose_name='Status (estado)')),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Linked Registered User')),
            ],
            options={
                'verbose_name': 'Solicited Product',
                'verbose_name_plural': 'Solicited Products',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Product name (snapshot)')),
                ('product_image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Product image (snapshot)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('price_at_order', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price at order')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order', verbose_name='Order (id_pedido)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Product (id_producto)')),
            ],
            options={
                'verbose_name': 'Ordered Product',
                'verbose_name_plural': 'Ordered Products',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='orders.OrderProduct', to='products.product', verbose_name='Ordered Products (productos_solicitados)'),
        ),
    ]
