# Generated by Django 5.2.8 on 2025-11-26 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('duration', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Discount')),
                ('endDiscount', models.DateTimeField(blank=True, db_column='endDiscount', null=True, verbose_name='End Discount Date')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'main_appointment',
            },
        ),
    ]
