# Generated by Django 4.2.26 on 2025-11-17 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('ref', models.CharField(max_length=50, unique=True, verbose_name='Reference/SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('flavor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Flavor')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total Price')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('EN_CARRITO', 'IN CART'), ('SOLICITADO', 'SOLICITED'), ('ENCARGADO', 'ORDERED'), ('RECIBIDO_NATURSUR', 'RECEIVED BY NATURSUR'), ('RECOGIDO_CLIENTE', 'PICKED UP BY CLIENT')], default='SOLICITADO', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('contact_email', models.EmailField(verbose_name='Contact Email')),
                ('notas', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),

        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product (id_producto)')),
            ],
            options={
                'verbose_name': 'Order Product',
                'verbose_name_plural': 'Order Products',
            },
        ),


        migrations.CreateModel(
            name='ProductSolicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitant_name', models.CharField(max_length=255, verbose_name='Solicitant Full Name (String)')),
                ('solicitant_contact', models.CharField(max_length=255, verbose_name='Solicitant Contact (Email/Phone)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid (estaPagado)')),
                ('status', models.CharField(choices=[('EN_CARRITO', 'IN CART'), ('SOLICITADO', 'SOLICITED'), ('ENCARGADO', 'ORDERED'), ('RECIBIDO_NATURSUR', 'RECEIVED BY NATURSUR'), ('RECOGIDO_CLIENTE', 'PICKED UP BY CLIENT')], default='SOLICITADO', max_length=20, verbose_name='Status (estado)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product (id_producto)')),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Linked Registered User')),
            ],
            options={
                'verbose_name': 'Solicited Product',
                'verbose_name_plural': 'Solicited Products',
            },
        ),
    ]
