# Generated by Django 5.2.8 on 2025-11-23 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_description_product_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Solicited Product', 'verbose_name_plural': 'Solicited Products'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Ordered Product', 'verbose_name_plural': 'Ordered Products'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='order',
            name='telephone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='anonymous_user_cookie',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Anonymous User Cookie'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is Paid (estaPagado)'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_identified',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Order Identifier'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='products.OrderProduct', to='products.product', verbose_name='Ordered Products (productos_solicitados)'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Linked Registered User'),
        ),
        migrations.AddField(
            model_name='order',
            name='solicitant_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Solicitant Address (optional)'),
        ),
        migrations.AddField(
            model_name='order',
            name='solicitant_contact',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Solicitant Contact (Email/Phone)'),
        ),
        migrations.AddField(
            model_name='order',
            name='solicitant_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Solicitant Full Name (String)'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='price_at_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Price at order'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('EN_CARRITO', 'IN CART'), ('SOLICITADO', 'SOLICITED'), ('ENCARGADO', 'ORDERED'), ('RECIBIDO_NATURSUR', 'RECEIVED BY NATURSUR'), ('RECOGIDO_CLIENTE', 'PICKED UP BY CLIENT')], default='SOLICITADO', max_length=20, verbose_name='Status (estado)'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='products.order', verbose_name='Order (id_pedido)'),
        ),
        migrations.DeleteModel(
            name='ProductSolicitation',
        ),
    ]
