# Generated by Django 5.2.8 on 2025-11-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsolicitation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsolicitation',
            name='registered_user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductSolicitation',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
